In [8]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.animation as animation


import plotly.express as px
import plotly.graph_objects as go
import plotly.figure_factory as ff

# Step 1: Loading Dataset

In [9]:
# Load the dataset
df = pd.read_csv("AMZN_quarterly_cash_flow.csv")

# Removing leading and trailing spaces from column names
df.columns = df.columns.str.strip()

# Using a regular expression to replace multiple spaces with a single space in all column names
df.columns = df.columns.str.replace(r'\s+', ' ', regex=True)

# Step 2: Overview of Dataset

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 29 columns):
 #   Column                                                     Non-Null Count  Dtype
---  ------                                                     --------------  -----
 0   fiscalDateEnding                                           61 non-null     object
 1   reportedCurrency                                           61 non-null     object
 2   operatingCashflow                                          61 non-null     int64
 3   paymentsForOperatingActivities                             58 non-null     float64
 4   proceedsFromOperatingActivities                            0 non-null      float64
 5   changeInOperatingLiabilities                               61 non-null     int64
 6   changeInOperatingAssets                                    61 non-null     int64
 7   depreciationDepletionAndAmortization                       61 non-null     int64
 8   capitalExpenditures                                        61 non-null     int64
 9   changeInReceivables                                        57 non-null     float64
 10  changeInInventory                                          61 non-null     int64
 11  profitLoss                                                 61 non-null     int64
 12  cashflowFromInvestment                                     61 non-null     int64
 13  cashflowFromFinancing                                      61 non-null     int64
 14  proceedsFromRepaymentsOfShortTermDebt                      22 non-null     float64
 15  paymentsForRepurchaseOfCommonStock                         61 non-null     int64
 16  paymentsForRepurchaseOfEquity                              61 non-null     int64
 17  paymentsForRepurchaseOfPreferredStock                      0 non-null      float64
 18  dividendPayout                                             0 non-null      float64
 19  dividendPayoutCommonStock                                  0 non-null      float64
 20  dividendPayoutPreferredStock                               0 non-null      float64
 21  proceedsFromIssuanceOfCommonStock                          0 non-null      float64
 22  proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet  36 non-null     float64
 23  proceedsFromIssuanceOfPreferredStock                       0 non-null      float64
 24  proceedsFromRepurchaseOfEquity                             53 non-null     float64
 25  proceedsFromSaleOfTreasuryStock                            0 non-null      float64
 26  changeInCashAndCashEquivalents                             57 non-null     float64
 27  changeInExchangeRate                                       51 non-null     float64
 28  netIncome                                                  61 non-null     int64
dtypes: float64(15), int64(12), object(2)
memory usage: 13.9+ KB

In [11]:
df.head(20)

,fiscalDateEnding,reportedCurrency,operatingCashflow,paymentsForOperatingActivities,proceedsFromOperatingActivities,changeInOperatingLiabilities,changeInOperatingAssets,depreciationDepletionAndAmortization,capitalExpenditures,changeInReceivables,...,dividendPayoutCommonStock,dividendPayoutPreferredStock,proceedsFromIssuanceOfCommonStock,proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet,proceedsFromIssuanceOfPreferredStock,proceedsFromRepurchaseOfEquity,proceedsFromSaleOfTreasuryStock,changeInCashAndCashEquivalents,changeInExchangeRate,netIncome
0,2024-06-30,USD,25281000000,2.916000e+09,NaN,6412000000,6140000000,12038000000,17620000000,NaN,...,NaN,NaN,NaN,0.000000e+00,NaN,0.000000e+00,NaN,NaN,NaN,13485000000
1,2024-03-31,USD,18989000000,3.406000e+09,NaN,-9714000000,925000000,11684000000,14925000000,NaN,...,NaN,NaN,NaN,0.000000e+00,NaN,0.000000e+00,NaN,NaN,NaN,10431000000
2,2023-12-31,USD,42465000000,2.840000e+09,NaN,14517000000,9622000000,13820000000,14588000000,NaN,...,NaN,NaN,NaN,0.000000e+00,NaN,0.000000e+00,NaN,NaN,NaN,10624000000
3,2023-09-30,USD,21217000000,2.768000e+09,NaN,2795000000,-808000000,12131000000,12479000000,NaN,...,NaN,NaN,NaN,0.000000e+00,NaN,0.000000e+00,NaN,NaN,NaN,9879000000
4,2023-06-30,USD,16476000000,2.605000e+09,NaN,3185000000,2373000000,11589000000,11455000000,-5.167000e+09,...,NaN,NaN,NaN,0.000000e+00,NaN,0.000000e+00,NaN,2.640000e+08,NaN,6750000000
5,2023-03-31,USD,4788000000,2.548000e+09,NaN,-10446000000,-371000000,11123000000,14207000000,1.521000e+09,...,NaN,NaN,NaN,0.000000e+00,NaN,0.000000e+00,NaN,-4.664000e+09,NaN,3172000000
6,2022-12-31,USD,29173000000,2.449000e+09,NaN,1300000000,-3180000000,12685000000,16592000000,-8.788000e+09,...,NaN,NaN,NaN,8.235000e+09,NaN,0.000000e+00,NaN,1.843800e+10,NaN,278000000
7,2022-09-30,USD,11404000000,1.901000e+09,NaN,-1172000000,-732000000,10327000000,16378000000,-4.794000e+09,...,NaN,NaN,NaN,1.070000e+08,NaN,0.000000e+00,NaN,-1.188000e+09,NaN,2872000000
8,2022-06-30,USD,8965000000,2.183000e+09,NaN,4020000000,3890000000,9716000000,15724000000,-6.799000e+09,...,NaN,NaN,NaN,1.282400e+10,NaN,-3.334000e+09,NaN,1.513000e+09,NaN,-2028000000
9,2022-03-31,USD,-2790000000,2.474000e+09,NaN,-8044000000,2614000000,9193000000,14951000000,-1.516000e+09,...,NaN,NaN,NaN,0.000000e+00,NaN,-2.666000e+09,NaN,1.060000e+08,NaN,-3844000000
10,2021-12-31,USD,22086000000,1.807000e+09,NaN,8909000000,1915000000,9939000000,18935000000,-6.556000e+09,...,NaN,NaN,NaN,2.000000e+08,NaN,0.000000e+00,NaN,6.300000e+09,-106000000.0,14323000000
11,2021-09-30,USD,7313000000,1.933000e+09,NaN,4170000000,7059000000,8948000000,15748000000,-4.890000e+09,...,NaN,NaN,NaN,1.760000e+08,NaN,0.000000e+00,NaN,-1.049000e+10,-199000000.0,3156000000
12,2021-06-30,USD,12715000000,1.706000e+09,NaN,203000000,209000000,8038000000,14288000000,-4.462000e+09,...,NaN,NaN,NaN,1.851600e+10,NaN,0.000000e+00,NaN,6.512000e+09,234000000.0,7778000000
13,2021-03-31,USD,4213000000,1.797000e+09,NaN,-7366000000,304000000,7508000000,12082000000,-2.255000e+09,...,NaN,NaN,NaN,1.110000e+08,NaN,0.000000e+00,NaN,-8.222000e+09,-293000000.0,8107000000
14,2020-12-31,USD,30431000000,1.328000e+09,NaN,13582000000,-329000000,7547000000,14823000000,-4.561000e+09,...,NaN,NaN,NaN,5.310000e+08,NaN,0.000000e+00,NaN,7.199000e+09,597000000.0,7222000000
15,2020-09-30,USD,11964000000,1.314000e+09,NaN,3736000000,3899000000,6523000000,11063000000,-2.016000e+09,...,NaN,NaN,NaN,0.000000e+00,NaN,0.000000e+00,NaN,-7.640000e+09,377000000.0,6331000000
16,2020-06-30,USD,20606000000,1.247000e+09,NaN,8863000000,672000000,5748000000,7459000000,-2.854000e+09,...,NaN,NaN,NaN,9.918000e+09,NaN,0.000000e+00,NaN,1.033700e+10,127000000.0,5243000000
17,2020-03-31,USD,3064000000,1.197000e+09,NaN,-7437000000,-1392000000,5362000000,6795000000,1.262000e+09,...,NaN,NaN,NaN,6.930000e+08,NaN,0.000000e+00,NaN,-8.905000e+09,-484000000.0,2535000000
18,2019-12-31,USD,19659000000,1.107000e+09,NaN,11169000000,1516000000,6170000000,5312000000,-3.905000e+09,...,NaN,NaN,NaN,1.098000e+09,NaN,0.000000e+00,NaN,3.267000e+09,304000000.0,3268000000
19,2019-09-30,USD,7892000000,1.039000e+09,NaN,173000000,381000000,5563000000,4697000000,-1.182000e+09,...,NaN,NaN,NaN,7.020000e+08,NaN,0.000000e+00,NaN,5.890000e+08,-269000000.0,2134000000

# Step 3: EDA - Missing Values Analysis

## Step 3)i): EDA - Show Missing Values in each Column

In [12]:
def display_columns_with_null_values(df: pd.DataFrame):
    """
    Displays the total number of null values for each column in the dataframe,
    showing only columns that have null values.
    
    Parameters:
    - df (pd.DataFrame): The dataframe to be checked for null values.
    
    Returns:
    - None: Prints the columns with null values and their counts.
    """
    
    # Get total null values in each column
    total_null_values = df.isnull().sum()
    
    # Filter out columns that don't have any null values
    columns_with_null = total_null_values[total_null_values > 0].sort_values(ascending=False)
    
    # Check if there are any columns with null values
    if not columns_with_null.empty:
        print('-' * 64)
        print("Total null values in each column (only columns with null values)")
        print('-' * 64)
        print(columns_with_null)
    else:
        print('-' * 64)
        print("Total null values in each column (only columns with null values)")
        print('-' * 64)
        print("No columns have null values.")

In [13]:
# Get percentage of null values in each column
null_values_percentage = df.isnull().mean().round(4).mul(100).sort_values(ascending=False)
print('-' * 44)
print("Percentage(%) of null values in each column")
print('-' * 44)
print(null_values_percentage)
print('\n')

# Get total null values in each column
display_columns_with_null_values(df)

--------------------------------------------
Percentage(%) of null values in each column
--------------------------------------------
proceedsFromOperatingActivities                              100.00
proceedsFromSaleOfTreasuryStock                              100.00
proceedsFromIssuanceOfPreferredStock                         100.00
proceedsFromIssuanceOfCommonStock                            100.00
dividendPayoutPreferredStock                                 100.00
dividendPayoutCommonStock                                    100.00
dividendPayout                                               100.00
paymentsForRepurchaseOfPreferredStock                        100.00
proceedsFromRepaymentsOfShortTermDebt                         63.93
proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet     40.98
changeInExchangeRate                                          16.39
proceedsFromRepurchaseOfEquity                                13.11
changeInCashAndCashEquivalents                                 6.56
changeInReceivables                                            6.56
paymentsForOperatingActivities                                 4.92
paymentsForRepurchaseOfEquity                                  0.00
fiscalDateEnding                                               0.00
paymentsForRepurchaseOfCommonStock                             0.00
reportedCurrency                                               0.00
cashflowFromFinancing                                          0.00
cashflowFromInvestment                                         0.00
profitLoss                                                     0.00
changeInInventory                                              0.00
capitalExpenditures                                            0.00
depreciationDepletionAndAmortization                           0.00
changeInOperatingAssets                                        0.00
changeInOperatingLiabilities                                   0.00
operatingCashflow                                              0.00
netIncome                                                      0.00
dtype: float64


----------------------------------------------------------------
Total null values in each column (only columns with null values)
----------------------------------------------------------------
proceedsFromOperatingActivities                              61
paymentsForRepurchaseOfPreferredStock                        61
dividendPayout                                               61
dividendPayoutCommonStock                                    61
dividendPayoutPreferredStock                                 61
proceedsFromIssuanceOfCommonStock                            61
proceedsFromIssuanceOfPreferredStock                         61
proceedsFromSaleOfTreasuryStock                              61
proceedsFromRepaymentsOfShortTermDebt                        39
proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet    25
changeInExchangeRate                                         10
proceedsFromRepurchaseOfEquity                                8
changeInReceivables                                           4
changeInCashAndCashEquivalents                                4
paymentsForOperatingActivities                                3
dtype: int64

## Step 3)ii): EDA - Handling Missing Values

In [14]:
# Drop Columns with Majority Null Values
"""
proceedsFromOperatingActivities                              61
paymentsForRepurchaseOfPreferredStock                        61
dividendPayout                                               61
dividendPayoutCommonStock                                    61
dividendPayoutPreferredStock                                 61
proceedsFromIssuanceOfCommonStock                            61
proceedsFromIssuanceOfPreferredStock                         61
proceedsFromSaleOfTreasuryStock                              61
proceedsFromRepaymentsOfShortTermDebt                        39
proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet    25
changeInExchangeRate                                         10
"""

df.drop([
    "proceedsFromOperatingActivities", 
    "paymentsForRepurchaseOfPreferredStock",
    "dividendPayout",
    "dividendPayoutCommonStock",
    "dividendPayoutPreferredStock",
    "proceedsFromIssuanceOfCommonStock",
    "proceedsFromIssuanceOfPreferredStock",
    "proceedsFromSaleOfTreasuryStock",
    "proceedsFromRepaymentsOfShortTermDebt",
    "proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet",
    "changeInExchangeRate"

         ], axis=1, inplace=True)

# Get total null values in each column
display_columns_with_null_values(df)

----------------------------------------------------------------
Total null values in each column (only columns with null values)
----------------------------------------------------------------
proceedsFromRepurchaseOfEquity    8
changeInReceivables               4
changeInCashAndCashEquivalents    4
paymentsForOperatingActivities    3
dtype: int64

In [15]:
# Fill Null Values in the Remaining Columns with the average of the column
numeric_df = df.select_dtypes(include=[np.number]) # Select only numeric columns
numeric_df.fillna(numeric_df.mean(), inplace=True)  # Fill missing values in numeric columns with the column mean
df[numeric_df.columns] = numeric_df # Merge back with non-numeric columns if needed

# Get total null values in each column
display_columns_with_null_values(df)

----------------------------------------------------------------
Total null values in each column (only columns with null values)
----------------------------------------------------------------
No columns have null values.

In [16]:
df.head(20)

,fiscalDateEnding,reportedCurrency,operatingCashflow,paymentsForOperatingActivities,changeInOperatingLiabilities,changeInOperatingAssets,depreciationDepletionAndAmortization,capitalExpenditures,changeInReceivables,changeInInventory,profitLoss,cashflowFromInvestment,cashflowFromFinancing,paymentsForRepurchaseOfCommonStock,paymentsForRepurchaseOfEquity,proceedsFromRepurchaseOfEquity,changeInCashAndCashEquivalents,netIncome
0,2024-06-30,USD,25281000000,2.916000e+09,6412000000,6140000000,12038000000,17620000000,-1.304035e+09,3085000000,13485000000,-22138000000,-4490000000,0,0,0.000000e+00,4.425965e+08,13485000000
1,2024-03-31,USD,18989000000,3.406000e+09,-9714000000,925000000,11684000000,14925000000,-1.304035e+09,-1776000000,10431000000,-17862000000,-1256000000,0,0,0.000000e+00,4.425965e+08,10431000000
2,2023-12-31,USD,42465000000,2.840000e+09,14517000000,9622000000,13820000000,14588000000,-1.304035e+09,-2643000000,10644000000,-12601000000,-6746000000,0,0,0.000000e+00,4.425965e+08,10624000000
3,2023-09-30,USD,21217000000,2.768000e+09,2795000000,-808000000,12131000000,12479000000,-1.304035e+09,-808000000,9879000000,-11753000000,-8948000000,0,0,0.000000e+00,4.425965e+08,9879000000
4,2023-06-30,USD,16476000000,2.605000e+09,3185000000,2373000000,11589000000,11455000000,-5.167000e+09,2373000000,6750000000,-9673000000,-6539000000,0,0,0.000000e+00,2.640000e+08,6750000000
5,2023-03-31,USD,4788000000,2.548000e+09,-10446000000,-371000000,11123000000,14207000000,1.521000e+09,-371000000,3172000000,-15806000000,6354000000,0,0,0.000000e+00,-4.664000e+09,3172000000
6,2022-12-31,USD,29173000000,2.449000e+09,1300000000,-3180000000,12685000000,16592000000,-8.788000e+09,-3180000000,-2720000000,-10821000000,86000000,0,0,0.000000e+00,1.843800e+10,278000000
7,2022-09-30,USD,11404000000,1.901000e+09,-1172000000,-732000000,10327000000,16378000000,-4.794000e+09,-732000000,2872000000,-15608000000,3016000000,0,0,0.000000e+00,-1.188000e+09,2872000000
8,2022-06-30,USD,8965000000,2.183000e+09,4020000000,3890000000,9716000000,15724000000,-6.799000e+09,3890000000,-2028000000,-12078000000,4626000000,3334000000,3334000000,-3.334000e+09,1.513000e+09,-2028000000
9,2022-03-31,USD,-2790000000,2.474000e+09,-8044000000,2614000000,9193000000,14951000000,-1.516000e+09,2614000000,-3844000000,906000000,1990000000,2666000000,2666000000,-2.666000e+09,1.060000e+08,-3844000000
10,2021-12-31,USD,22086000000,1.807000e+09,8909000000,1915000000,9939000000,18935000000,-6.556000e+09,1915000000,14314000000,-12580000000,-3100000000,0,0,0.000000e+00,6.300000e+09,14323000000
11,2021-09-30,USD,7313000000,1.933000e+09,4170000000,7059000000,8948000000,15748000000,-4.890000e+09,7059000000,3156000000,-14828000000,-2776000000,0,0,0.000000e+00,-1.049000e+10,3156000000
12,2021-06-30,USD,12715000000,1.706000e+09,203000000,209000000,8038000000,14288000000,-4.462000e+09,209000000,7778000000,-22080000000,15643000000,0,0,0.000000e+00,6.512000e+09,7778000000
13,2021-03-31,USD,4213000000,1.797000e+09,-7366000000,304000000,7508000000,12082000000,-2.255000e+09,304000000,8107000000,-8666000000,-3476000000,0,0,0.000000e+00,-8.222000e+09,8107000000
14,2020-12-31,USD,30431000000,1.328000e+09,13582000000,-329000000,7547000000,14823000000,-4.561000e+09,-329000000,7199000000,-17037000000,-1816000000,0,0,0.000000e+00,7.199000e+09,7222000000
15,2020-09-30,USD,11964000000,1.314000e+09,3736000000,3899000000,6523000000,11063000000,-2.016000e+09,3899000000,6331000000,-15876000000,-4105000000,0,0,0.000000e+00,-7.640000e+09,6331000000
16,2020-06-30,USD,20606000000,1.247000e+09,8863000000,672000000,5748000000,7459000000,-2.854000e+09,672000000,5243000000,-17804000000,7408000000,0,0,0.000000e+00,1.033700e+10,5243000000
17,2020-03-31,USD,3064000000,1.197000e+09,-7437000000,-1392000000,5362000000,6795000000,1.262000e+09,-1392000000,2535000000,-8894000000,-2591000000,0,0,0.000000e+00,-8.905000e+09,2535000000
18,2019-12-31,USD,19659000000,1.107000e+09,11169000000,1516000000,6170000000,5312000000,-3.905000e+09,1516000000,3267000000,-3536000000,-3571000000,0,0,0.000000e+00,3.267000e+09,3268000000
19,2019-09-30,USD,7892000000,1.039000e+09,173000000,381000000,5563000000,4697000000,-1.182000e+09,381000000,2134000000,-5074000000,-1960000000,0,0,0.000000e+00,5.890000e+08,2134000000

# Step 4: EDA - Duplicate Values Analysis

## Step 4)i): EDA - Show Duplicate Values Rows

In [17]:
# Get percentage of duplicate rows
total_rows = len(df)
duplicate_rows = df.duplicated().sum()
duplicate_percentage = (duplicate_rows / total_rows) * 100

print('-' * 48)
print("Percentage(%) of duplicate rows in the DataFrame")
print('-' * 48)
print(f"{duplicate_percentage:.2f}%")
print('\n')

# Get total number of duplicate rows
print('-' * 30)
print("Total number of duplicate rows")
print('-' * 30)
print(duplicate_rows)

------------------------------------------------
Percentage(%) of duplicate rows in the DataFrame
------------------------------------------------
0.00%


------------------------------
Total number of duplicate rows
------------------------------
0

## Step 4)ii): EDA - Handling Duplicate Values Rows

In [18]:
# # Drop all duplicate rows
# df_cleaned = df.drop_duplicates()

# print('-' * 22)
# print("Duplicate rows dropped")
# print('-' * 22)
# print(f"Original number of rows: {total_rows}")
# print(f"Number of rows after dropping duplicates: {len(df_cleaned)}")

# Step 5): EDA - Save Cleaned Dataset

In [19]:
# save to csv
df.to_csv(f'DC_AMZN_quarterly_cash_flow.csv')