In [37]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.animation as animation


import plotly.express as px
import plotly.graph_objects as go
import plotly.figure_factory as ff

# Step 1: Loading Dataset

In [38]:
# Load the dataset
df = pd.read_csv("AMZN_quarterly_balance_sheet.csv")

# Removing leading and trailing spaces from column names
df.columns = df.columns.str.strip()

# Using a regular expression to replace multiple spaces with a single space in all column names
df.columns = df.columns.str.replace(r'\s+', ' ', regex=True)

# Step 2: Overview of Dataset

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 38 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   fiscalDateEnding                        61 non-null     object
 1   reportedCurrency                        61 non-null     object
 2   totalAssets                             61 non-null     int64
 3   totalCurrentAssets                      61 non-null     int64
 4   cashAndCashEquivalentsAtCarryingValue   61 non-null     int64
 5   cashAndShortTermInvestments             61 non-null     int64
 6   inventory                               61 non-null     int64
 7   currentNetReceivables                   61 non-null     int64
 8   totalNonCurrentAssets                   61 non-null     int64
 9   propertyPlantEquipment                  61 non-null     int64
 10  accumulatedDepreciationAmortizationPPE  11 non-null     float64
 11  intangibleAssets                        61 non-null     int64
 12  intangibleAssetsExcludingGoodwill       44 non-null     float64
 13  goodwill                                61 non-null     int64
 14  investments                             39 non-null     float64
 15  longTermInvestments                     11 non-null     float64
 16  shortTermInvestments                    61 non-null     int64
 17  otherCurrentAssets                      61 non-null     int64
 18  otherNonCurrentAssets                   61 non-null     int64
 19  totalLiabilities                        61 non-null     int64
 20  totalCurrentLiabilities                 61 non-null     int64
 21  currentAccountsPayable                  60 non-null     float64
 22  deferredRevenue                         39 non-null     float64
 23  currentDebt                             48 non-null     float64
 24  shortTermDebt                           47 non-null     float64
 25  totalNonCurrentLiabilities              61 non-null     int64
 26  capitalLeaseObligations                 22 non-null     float64
 27  longTermDebt                            55 non-null     float64
 28  currentLongTermDebt                     48 non-null     float64
 29  longTermDebtNoncurrent                  55 non-null     float64
 30  shortLongTermDebtTotal                  56 non-null     float64
 31  otherCurrentLiabilities                 61 non-null     int64
 32  otherNonCurrentLiabilities              55 non-null     float64
 33  totalShareholderEquity                  61 non-null     int64
 34  treasuryStock                           61 non-null     int64
 35  retainedEarnings                        61 non-null     int64
 36  commonStock                             61 non-null     int64
 37  commonStockSharesOutstanding            61 non-null     int64
dtypes: float64(14), int64(22), object(2)
memory usage: 18.2+ KB

In [40]:
df.head(20)

,fiscalDateEnding,reportedCurrency,totalAssets,totalCurrentAssets,cashAndCashEquivalentsAtCarryingValue,cashAndShortTermInvestments,inventory,currentNetReceivables,totalNonCurrentAssets,propertyPlantEquipment,...,currentLongTermDebt,longTermDebtNoncurrent,shortLongTermDebtTotal,otherCurrentLiabilities,otherNonCurrentLiabilities,totalShareholderEquity,treasuryStock,retainedEarnings,commonStock,commonStockSharesOutstanding
0,2024-06-30,USD,554818000000,173307000000,71178000000,89092000000,34109000000,50106000000,160798000000,220717000000,...,7.429000e+09,5.488900e+10,6.275900e+10,42747000000,2.722600e+10,236447000000,7837000000,137534000000,110000000,10490000000
1,2024-03-31,USD,530969000000,163989000000,72852000000,85074000000,31147000000,47768000000,157036000000,209950000000,...,8.848000e+09,5.763400e+10,6.690200e+10,44915000000,2.665700e+10,216661000000,7837000000,124049000000,109000000,10403000000
2,2023-12-31,USD,527854000000,172351000000,73387000000,86780000000,33318000000,52253000000,159019000000,204177000000,...,8.494000e+09,5.831400e+10,6.732900e+10,45764000000,2.545100e+10,201875000000,7837000000,113618000000,109000000,10383000000
3,2023-09-30,USD,486883000000,142995000000,49605000000,64169000000,35406000000,43420000000,147431000000,196468000000,...,5.995000e+09,6.109800e+10,6.763800e+10,42340000000,2.170700e+10,182973000000,7837000000,102994000000,108000000,10330000000
4,2023-06-30,USD,477607000000,140482000000,49529000000,63970000000,36587000000,39925000000,143356000000,193784000000,...,3.997000e+09,6.309200e+10,6.857200e+10,49232000000,2.185300e+10,168602000000,7837000000,93115000000,108000000,10313000000
5,2023-03-31,USD,464378000000,136221000000,49343000000,64405000000,34170000000,37646000000,137417000000,190754000000,...,2.000000e+09,6.708400e+10,7.057200e+10,66382000000,2.093100e+10,154526000000,7837000000,86365000000,108000000,10258000000
6,2022-12-31,USD,462675000000,146791000000,53888000000,70026000000,34405000000,42360000000,135273000000,186715000000,...,2.999000e+09,6.715000e+10,7.174200e+10,62566000000,2.112100e+10,146043000000,7837000000,83193000000,108000000,10242000000
7,2022-09-30,USD,428362000000,131463000000,34947000000,58662000000,36647000000,36154000000,119711000000,177195000000,...,4.247000e+09,5.891900e+10,6.464100e+10,59974000000,2.225900e+10,137489000000,7837000000,82915000000,107000000,10198000000
8,2022-06-30,USD,419728000000,133667000000,37478000000,60710000000,38153000000,34804000000,112370000000,173706000000,...,4.998000e+09,5.805300e+10,6.367000e+10,56254000000,2.345800e+10,131402000000,7837000000,80043000000,107000000,10183000000
9,2022-03-31,USD,410767000000,133876000000,36393000000,66385000000,34987000000,32504000000,108438000000,168468000000,...,2.681000e+09,4.755600e+10,5.055300e+10,58141000000,2.397100e+10,134001000000,4503000000,82071000000,5000000,509000000
10,2021-12-31,USD,420549000000,161580000000,36220000000,96049000000,32640000000,32891000000,103810000000,160281000000,...,1.491000e+09,4.874400e+10,5.087100e+10,35852000000,2.364300e+10,138245000000,1837000000,85915000000,106000000,509000000
11,2021-09-30,USD,382406000000,138531000000,29944000000,78988000000,30933000000,28610000000,96738000000,147152000000,...,1.000000e+09,5.005500e+10,5.137600e+10,25921000000,2.394500e+10,120564000000,1837000000,71592000000,5000000,507000000
12,2021-06-30,USD,360319000000,140848000000,40380000000,89894000000,24119000000,26835000000,85991000000,133502000000,...,1.158000e+09,5.027900e+10,5.176200e+10,25193000000,2.114800e+10,114803000000,1837000000,68436000000,5000000,506000000
13,2021-03-31,USD,323077000000,121408000000,33834000000,73270000000,23849000000,24289000000,149530000000,52161000000,...,1.156000e+09,3.186800e+10,3.322700e+10,39058000000,1.941800e+10,103320000000,1837000000,60658000000,5000000,504000000
14,2020-12-31,USD,321195000000,132733000000,42122000000,84396000000,23795000000,24542000000,148451000000,45014000000,...,1.155000e+09,3.181600e+10,3.317400e+10,42147000000,1.701700e+10,93404000000,1837000000,52551000000,5000000,503000000
15,2020-09-30,USD,282179000000,112969000000,29930000000,68402000000,23735000000,20832000000,234143000000,99981000000,...,1.550000e+08,3.292900e+10,3.328800e+10,33447000000,1.597400e+10,82775000000,1837000000,45329000000,5000000,502000000
16,2020-06-30,USD,258314000000,110908000000,37466000000,71391000000,19599000000,19918000000,208228000000,86517000000,...,1.154000e+09,3.312800e+10,3.448600e+10,31979000000,1.476400e+10,73728000000,1837000000,38998000000,5000000,501000000
17,2020-03-31,USD,221238000000,85985000000,27201000000,49292000000,18857000000,17836000000,193275000000,77779000000,...,1.311000e+09,2.343700e+10,2.484900e+10,29480000000,1.251800e+10,65272000000,1837000000,33755000000,5000000,499000000
18,2019-12-31,USD,225248000000,96334000000,36092000000,55021000000,20497000000,20816000000,190405000000,72705000000,...,1.305000e+09,2.341400e+10,2.482000e+10,31134000000,1.217100e+10,62060000000,1837000000,31220000000,5000000,498000000
19,2019-09-30,USD,199099000000,79054000000,23255000000,43401000000,18766000000,16887000000,173787000000,67662000000,...,2.841000e+09,2.247200e+10,2.541100e+10,26120000000,1.092500e+10,56508000000,1837000000,27952000000,5000000,495000000

# Step 3: EDA - Missing Values Analysis

## Step 3)i): EDA - Show Missing Values in each Column

In [41]:
def display_columns_with_null_values(df: pd.DataFrame):
    """
    Displays the total number of null values for each column in the dataframe,
    showing only columns that have null values.
    
    Parameters:
    - df (pd.DataFrame): The dataframe to be checked for null values.
    
    Returns:
    - None: Prints the columns with null values and their counts.
    """
    
    # Get total null values in each column
    total_null_values = df.isnull().sum()
    
    # Filter out columns that don't have any null values
    columns_with_null = total_null_values[total_null_values > 0].sort_values(ascending=False)
    
    # Check if there are any columns with null values
    if not columns_with_null.empty:
        print('-' * 64)
        print("Total null values in each column (only columns with null values)")
        print('-' * 64)
        print(columns_with_null)
    else:
        print('-' * 64)
        print("Total null values in each column (only columns with null values)")
        print('-' * 64)
        print("No columns have null values.")

In [42]:
# Get percentage of null values in each column
null_values_percentage = df.isnull().mean().round(4).mul(100).sort_values(ascending=False)
print('-' * 44)
print("Percentage(%) of null values in each column")
print('-' * 44)
print(null_values_percentage)
print('\n')

# Get total null values in each column
display_columns_with_null_values(df)

--------------------------------------------
Percentage(%) of null values in each column
--------------------------------------------
accumulatedDepreciationAmortizationPPE    81.97
longTermInvestments                       81.97
capitalLeaseObligations                   63.93
investments                               36.07
deferredRevenue                           36.07
intangibleAssetsExcludingGoodwill         27.87
shortTermDebt                             22.95
currentLongTermDebt                       21.31
currentDebt                               21.31
otherNonCurrentLiabilities                 9.84
longTermDebtNoncurrent                     9.84
longTermDebt                               9.84
shortLongTermDebtTotal                     8.20
currentAccountsPayable                     1.64
totalShareholderEquity                     0.00
otherCurrentLiabilities                    0.00
treasuryStock                              0.00
retainedEarnings                           0.00
commonStock                                0.00
totalNonCurrentLiabilities                 0.00
fiscalDateEnding                           0.00
totalLiabilities                           0.00
totalCurrentLiabilities                    0.00
reportedCurrency                           0.00
otherNonCurrentAssets                      0.00
otherCurrentAssets                         0.00
shortTermInvestments                       0.00
goodwill                                   0.00
intangibleAssets                           0.00
propertyPlantEquipment                     0.00
totalNonCurrentAssets                      0.00
currentNetReceivables                      0.00
inventory                                  0.00
cashAndShortTermInvestments                0.00
cashAndCashEquivalentsAtCarryingValue      0.00
totalCurrentAssets                         0.00
totalAssets                                0.00
commonStockSharesOutstanding               0.00
dtype: float64


----------------------------------------------------------------
Total null values in each column (only columns with null values)
----------------------------------------------------------------
accumulatedDepreciationAmortizationPPE    50
longTermInvestments                       50
capitalLeaseObligations                   39
investments                               22
deferredRevenue                           22
intangibleAssetsExcludingGoodwill         17
shortTermDebt                             14
currentDebt                               13
currentLongTermDebt                       13
longTermDebt                               6
longTermDebtNoncurrent                     6
otherNonCurrentLiabilities                 6
shortLongTermDebtTotal                     5
currentAccountsPayable                     1
dtype: int64

## Step 3)ii): EDA - Handling Missing Values

In [43]:
# Drop Columns with Majority Null Values

"""
accumulatedDepreciationAmortizationPPE    50
longTermInvestments                       50
capitalLeaseObligations                   39
investments                               22
deferredRevenue                           22
intangibleAssetsExcludingGoodwill         17
shortTermDebt                             14
currentDebt                               13
currentLongTermDebt                       13
"""

df.drop(["accumulatedDepreciationAmortizationPPE", 
         "longTermInvestments",
         "capitalLeaseObligations",
         "investments",
        "deferredRevenue",
        "intangibleAssetsExcludingGoodwill",
        "shortTermDebt",
        "currentDebt",
        "currentLongTermDebt"

         ], axis=1, inplace=True)

# Get total null values in each column
display_columns_with_null_values(df)

----------------------------------------------------------------
Total null values in each column (only columns with null values)
----------------------------------------------------------------
longTermDebt                  6
longTermDebtNoncurrent        6
otherNonCurrentLiabilities    6
shortLongTermDebtTotal        5
currentAccountsPayable        1
dtype: int64

In [44]:
# Fill Null Values in the Remaining Columns with the average of the column
numeric_df = df.select_dtypes(include=[np.number]) # Select only numeric columns
numeric_df.fillna(numeric_df.mean(), inplace=True)  # Fill missing values in numeric columns with the column mean
df[numeric_df.columns] = numeric_df # Merge back with non-numeric columns if needed

# Get total null values in each column
display_columns_with_null_values(df)

----------------------------------------------------------------
Total null values in each column (only columns with null values)
----------------------------------------------------------------
No columns have null values.

In [45]:
df.head(20)

,fiscalDateEnding,reportedCurrency,totalAssets,totalCurrentAssets,cashAndCashEquivalentsAtCarryingValue,cashAndShortTermInvestments,inventory,currentNetReceivables,totalNonCurrentAssets,propertyPlantEquipment,...,longTermDebt,longTermDebtNoncurrent,shortLongTermDebtTotal,otherCurrentLiabilities,otherNonCurrentLiabilities,totalShareholderEquity,treasuryStock,retainedEarnings,commonStock,commonStockSharesOutstanding
0,2024-06-30,USD,554818000000,173307000000,71178000000,89092000000,34109000000,50106000000,160798000000,220717000000,...,6.268300e+10,5.488900e+10,6.275900e+10,42747000000,2.722600e+10,236447000000,7837000000,137534000000,110000000,10490000000
1,2024-03-31,USD,530969000000,163989000000,72852000000,85074000000,31147000000,47768000000,157036000000,209950000000,...,6.685200e+10,5.763400e+10,6.690200e+10,44915000000,2.665700e+10,216661000000,7837000000,124049000000,109000000,10403000000
2,2023-12-31,USD,527854000000,172351000000,73387000000,86780000000,33318000000,52253000000,159019000000,204177000000,...,6.718200e+10,5.831400e+10,6.732900e+10,45764000000,2.545100e+10,201875000000,7837000000,113618000000,109000000,10383000000
3,2023-09-30,USD,486883000000,142995000000,49605000000,64169000000,35406000000,43420000000,147431000000,196468000000,...,6.747200e+10,6.109800e+10,6.763800e+10,42340000000,2.170700e+10,182973000000,7837000000,102994000000,108000000,10330000000
4,2023-06-30,USD,477607000000,140482000000,49529000000,63970000000,36587000000,39925000000,143356000000,193784000000,...,6.747200e+10,6.309200e+10,6.857200e+10,49232000000,2.185300e+10,168602000000,7837000000,93115000000,108000000,10313000000
5,2023-03-31,USD,464378000000,136221000000,49343000000,64405000000,34170000000,37646000000,137417000000,190754000000,...,6.947200e+10,6.708400e+10,7.057200e+10,66382000000,2.093100e+10,154526000000,7837000000,86365000000,108000000,10258000000
6,2022-12-31,USD,462675000000,146791000000,53888000000,70026000000,34405000000,42360000000,135273000000,186715000000,...,7.054200e+10,6.715000e+10,7.174200e+10,62566000000,2.112100e+10,146043000000,7837000000,83193000000,108000000,10242000000
7,2022-09-30,USD,428362000000,131463000000,34947000000,58662000000,36647000000,36154000000,119711000000,177195000000,...,6.354100e+10,5.891900e+10,6.464100e+10,59974000000,2.225900e+10,137489000000,7837000000,82915000000,107000000,10198000000
8,2022-06-30,USD,419728000000,133667000000,37478000000,60710000000,38153000000,34804000000,112370000000,173706000000,...,6.343500e+10,5.805300e+10,6.367000e+10,56254000000,2.345800e+10,131402000000,7837000000,80043000000,107000000,10183000000
9,2022-03-31,USD,410767000000,133876000000,36393000000,66385000000,34987000000,32504000000,108438000000,168468000000,...,5.055300e+10,4.755600e+10,5.055300e+10,58141000000,2.397100e+10,134001000000,4503000000,82071000000,5000000,509000000
10,2021-12-31,USD,420549000000,161580000000,36220000000,96049000000,32640000000,32891000000,103810000000,160281000000,...,5.055300e+10,4.874400e+10,5.087100e+10,35852000000,2.364300e+10,138245000000,1837000000,85915000000,106000000,509000000
11,2021-09-30,USD,382406000000,138531000000,29944000000,78988000000,30933000000,28610000000,96738000000,147152000000,...,5.137600e+10,5.005500e+10,5.137600e+10,25921000000,2.394500e+10,120564000000,1837000000,71592000000,5000000,507000000
12,2021-06-30,USD,360319000000,140848000000,40380000000,89894000000,24119000000,26835000000,85991000000,133502000000,...,5.176200e+10,5.027900e+10,5.176200e+10,25193000000,2.114800e+10,114803000000,1837000000,68436000000,5000000,506000000
13,2021-03-31,USD,323077000000,121408000000,33834000000,73270000000,23849000000,24289000000,149530000000,52161000000,...,3.322700e+10,3.186800e+10,3.322700e+10,39058000000,1.941800e+10,103320000000,1837000000,60658000000,5000000,504000000
14,2020-12-31,USD,321195000000,132733000000,42122000000,84396000000,23795000000,24542000000,148451000000,45014000000,...,3.317400e+10,3.181600e+10,3.317400e+10,42147000000,1.701700e+10,93404000000,1837000000,52551000000,5000000,503000000
15,2020-09-30,USD,282179000000,112969000000,29930000000,68402000000,23735000000,20832000000,234143000000,99981000000,...,3.328800e+10,3.292900e+10,3.328800e+10,33447000000,1.597400e+10,82775000000,1837000000,45329000000,5000000,502000000
16,2020-06-30,USD,258314000000,110908000000,37466000000,71391000000,19599000000,19918000000,208228000000,86517000000,...,3.448600e+10,3.312800e+10,3.448600e+10,31979000000,1.476400e+10,73728000000,1837000000,38998000000,5000000,501000000
17,2020-03-31,USD,221238000000,85985000000,27201000000,49292000000,18857000000,17836000000,193275000000,77779000000,...,2.484900e+10,2.343700e+10,2.484900e+10,29480000000,1.251800e+10,65272000000,1837000000,33755000000,5000000,499000000
18,2019-12-31,USD,225248000000,96334000000,36092000000,55021000000,20497000000,20816000000,190405000000,72705000000,...,2.482000e+10,2.341400e+10,2.482000e+10,31134000000,1.217100e+10,62060000000,1837000000,31220000000,5000000,498000000
19,2019-09-30,USD,199099000000,79054000000,23255000000,43401000000,18766000000,16887000000,173787000000,67662000000,...,2.541100e+10,2.247200e+10,2.541100e+10,26120000000,1.092500e+10,56508000000,1837000000,27952000000,5000000,495000000

# Step 4: EDA - Duplicate Values Analysis

## Step 4)i): EDA - Show Duplicate Values Rows

In [46]:
# Get percentage of duplicate rows
total_rows = len(df)
duplicate_rows = df.duplicated().sum()
duplicate_percentage = (duplicate_rows / total_rows) * 100

print('-' * 48)
print("Percentage(%) of duplicate rows in the DataFrame")
print('-' * 48)
print(f"{duplicate_percentage:.2f}%")
print('\n')

# Get total number of duplicate rows
print('-' * 30)
print("Total number of duplicate rows")
print('-' * 30)
print(duplicate_rows)

------------------------------------------------
Percentage(%) of duplicate rows in the DataFrame
------------------------------------------------
0.00%


------------------------------
Total number of duplicate rows
------------------------------
0

## Step 4)ii): EDA - Handling Duplicate Values Rows

In [47]:
# # Drop all duplicate rows
# df_cleaned = df.drop_duplicates()

# print('-' * 22)
# print("Duplicate rows dropped")
# print('-' * 22)
# print(f"Original number of rows: {total_rows}")
# print(f"Number of rows after dropping duplicates: {len(df_cleaned)}")

# Step 5): EDA - Save Cleaned Dataset

In [48]:
# save to csv
df.to_csv(f'DC_AMZN_quarterly_balance_sheet.csv.csv')